Code cleanup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
 # Configure script for 'prwd'
-# Copyright (c) 2012-2013 Bertrand Janin <b@janin.com>
+# Copyright (c) 2012-2014 Bertrand Janin <b@janin.com>
 #
 #
 
-PRWD_VERSION="1.9"
+VERSION="1.9"
 
 
 # Some shells have shitty echos
@@ -24,7 +24,11 @@ generate_makefile() {
 	echo "# Automagically generated by 'configure'"
 	echo
 
-	echo "CFLAGS+=$CFLAGS -DPRWD_VERSION=\\\"$PRWD_VERSION\\\" $X_CFLAGS"
+	echo "CFLAGS+=$CFLAGS -std=c99 -pedantic"
+	echo "CFLAGS+=-Wall -W -Wpointer-arith -Wbad-function-cast -Wcast-qual"
+	echo "CFLAGS+=-Wstrict-prototypes -Wmissing-prototypes"
+	echo "CFLAGS+=-Wmissing-declarations -Wnested-externs -Winline"
+	echo "CFLAGS+=-DVERSION=\\\"$VERSION\\\" $X_CFLAGS"
 
 	if [ "$DEBUG_MODE" = "Y" ]; then
 		echo "CFLAGS+=-Wall -ggdb -O0"
@@ -202,6 +206,20 @@ else
 	echo yes
 fi
 rm -f fake_wcslcpy*
+
+# Check if we have wcstonum
+echo -n "wcstonum... "
+cat <<EOF > fake_wcstonum.c
+main() { int i; const char *errstr; i = wcstonum("42", 1, 64, &errstr); }
+EOF
+if ! ${CC} fake_wcstonum.c -o /dev/null 1>/dev/null 2>/dev/null; then
+	echo "not found (we'll use ours)"
+	X_OBJECTS="$X_OBJECTS wcstonum.o"
+	CFLAGS="$CFLAGS -DHAS_NO_wcstoNUM"
+else
+	echo yes
+fi
+rm -f fake_wcstonum*
 
 
 generate_makefile Makefile.src > Makefile
